import Head from "next/head";
import Image from "next/image";
import HeroImage from "@/images/hero2_img.png";
import UnderLine from "@/images/fllatLine.png";
import {
  Footer,
  Navbar,
  PrimaryButton,
  ReviewCard,
  SearchInput,
  Tab
} from "@/components";
import {
  AboutUsImage,
  AboutUsSection,
  AboutUsText,
  AppButton,
  AppButtons,
  Banner,
  Body,
  GOAImage,
  GOATextDiv,
  GetOurApp,
  HeroBody,
  HeroSection,
  NewListingsButton,
  NewListingsCards,
  NewListingsHeader,
  NewListingsSection,
  NewListingsTab,
  NewListingsTopBar,
  Property,
  PropertyDiv,
  PropertyIdentifier,
  PropertyNumber,
  ReviewButton,
  Reviews,
  ReviewsHeader,
  ReviewsSection,
  SearchBar,
  SquiglyLine,
  SquiglyLineTwin,
  TextUnderline,
  VertcalLine,
  WelcomeText
} from "@/styles/home.styles";
import AppStoreBtn from "@/images/share/app_store.png";
import GooglePlayBtn from "@/images/share/google_play.png";
import PhoneImg from "@/images/share/phone_img.png";
import ReviewPointer from "@/images/squiglyLine.png";
import AboutUsImg from "@/images/about-us-img.png";
import { useState } from "react";
import { PropertyCard } from "@/components/cards/propertyCard";

export default function Home() {
  const ReviewsMockData = [
    {
      name: "Okpara Fred",
      location: "Wuse, Abuja.",
      review:
        "I purchased through Housinn and found their level of service to be above and beyond and I would highly recommend them to any future purchasers if they require a great level of service."
    },
    {
      name: "Ajoke Ademola",
      location: "Owerri, Imo.",
      review:
        "I was very impressed with this company. From the initial assignment by our agent it was a great experience."
    },
    {
      name: "Onu Samuel",
      location: "Lekki, Lagos.",
      review:
        "Buying a house from Housinn was one of the best decisions, I've ever made, their services were amazing and every transaction made were seamless and transparent."
    }
  ];

  const TabData = ["House", "Flat", "Land"];
  const [activeTab, setActiveTab] = useState(TabData[0]);
  return (
    <>
      <Head>
        <title>Housinn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Housinn</title>
        <link
          href="https://fonts.cdnfonts.com/css/open-sans"
          rel="stylesheet"
        ></link>
      </Head>
      <Body>
        <HeroSection>
          <Banner>
            <Image
              src={HeroImage}
              alt="hero Image"
              fill={true}
              objectFit="cover"
            />
          </Banner>
          <Navbar />
          <HeroBody>
            <WelcomeText>
              Your Key to Extraordinary Living
              <br />
              <span style={{ position: "relative" }}>
                Begins Here
                <TextUnderline>
                  <Image src={UnderLine} alt="line" />
                </TextUnderline>
              </span>
            </WelcomeText>
            <SearchBar>
              <SearchInput placeholder="Search by address, neighborhood, city or state" />
            </SearchBar>
          </HeroBody>
        </HeroSection>
        <NewListingsSection>
          <NewListingsTopBar>
            <NewListingsHeader>New Listings</NewListingsHeader>
            <NewListingsTab>
              <Tab
                options={TabData}
                setTab={setActiveTab}
                activeTab={activeTab}
              />
            </NewListingsTab>
          </NewListingsTopBar>
          <NewListingsCards>
            <PropertyCard tagType="sale" />
            <PropertyCard />
            <PropertyCard tagType="sale" />
            <PropertyCard />
            <PropertyCard tagType="sale" />
            <PropertyCard />
          </NewListingsCards>
          <NewListingsButton>
            <PrimaryButton text="View all Listings" />
          </NewListingsButton>
        </NewListingsSection>
        <AboutUsSection>
          <AboutUsText>
            <h3>About Us</h3>
            <p>
              Here At Housinn, we believe that finding the perfect place to call
              home should be a seamless and enjoyable experience. Whether you're
              in search of a cozy house, a modern apartment, a vast piece of
              land, or any other property type, we are here to guide you every
              step of the way. With a passion for real estate and a commitment
              to exceptional service, Housinn is your ultimate destination for
              all your property needs.
            </p>
            <PropertyDiv>
              <Property>
                <PropertyNumber>100K+</PropertyNumber>
                <PropertyIdentifier>Properties Listed</PropertyIdentifier>
              </Property>
              <VertcalLine />
              <Property>
                <PropertyNumber>30K+</PropertyNumber>
                <PropertyIdentifier>Properties Sold</PropertyIdentifier>
              </Property>
            </PropertyDiv>
          </AboutUsText>
          <AboutUsImage>
            <Image src={AboutUsImg} alt="about-us" />
          </AboutUsImage>
        </AboutUsSection>
        <ReviewsSection>
          <ReviewsHeader>What Our Customers Are Saying</ReviewsHeader>
          <Reviews>
            <SquiglyLine>
              <Image src={ReviewPointer} alt="points" />
            </SquiglyLine>
            <SquiglyLineTwin>
              <Image src={ReviewPointer} alt="points" />
            </SquiglyLineTwin>
            {ReviewsMockData.map((item, i) => {
              return (
                <ReviewCard
                  key={i}
                  name={item.name}
                  location={item.location}
                  review={item.review}
                />
              );
            })}
          </Reviews>
          <ReviewButton>
            <PrimaryButton text="Read Reviews" />
          </ReviewButton>
        </ReviewsSection>
        <GetOurApp>
          <GOATextDiv>
            <h2>Get Our App</h2>
            <h3>
              Download our Android app or iOS app to get quick access to
              property on Housinn from your mobile phone.
            </h3>
            <AppButtons>
              <AppButton>
                <Image src={AppStoreBtn} alt="app-store" />
              </AppButton>
              <AppButton>
                <Image src={GooglePlayBtn} alt="google-play" />
              </AppButton>
            </AppButtons>
          </GOATextDiv>
          <GOAImage>
            <Image src={PhoneImg} alt="Get-our-app-img" />
          </GOAImage>
        </GetOurApp>
        <Footer />
      </Body>
    </>
  );
}
